name: Integration Test
run-name: "Integration Test (${{ inputs.fmsgd_ref }})"

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      fmsgd_ref:
        description: 'fmsgd branch/ref to test'
        required: false
        default: 'main'
      fmsgid_ref:
        description: 'fmsgid branch/ref to test'
        required: false
        default: 'main'
      fmsg_webapi_ref:
        description: 'fmsg-webapi branch/ref to test'
        required: false
        default: 'main'
      fmsg_cli_ref:
        description: 'fmsg-cli branch/ref to test'
        required: false
        default: 'main'

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Run integration tests
        run: bash test/run-tests.sh
        env:
          FMSGD_REF: ${{ github.event.inputs.fmsgd_ref }}
          FMSGID_REF: ${{ github.event.inputs.fmsgid_ref }}
          FMSG_WEBAPI_REF: ${{ github.event.inputs.fmsg_webapi_ref }}
          FMSG_CLI_REF: ${{ github.event.inputs.fmsg_cli_ref }}

      - name: Cleanup
        if: always()
        run: bash test/run-tests.sh cleanup
